### ISSUE TITLE
Question Variant config.yml and Question more complex replacement

### ISSUE THREAD

**Issue by M1B4ND** [felixstaude/Emotes#5]
1) Can we put several variants of a word or do we have to specify the word each time?
```
replacements:
  kok: ""
  KOK: ""
```
or is there another solution?

2) Is there any way to get back to :Kappa: too?
I've tried but it doesn't work, maybe it's not possible at the moment.
```
replacements:
  kok: ""
  :Kappa:: ""
```

**Comment by felixstaude** [comment]
i will do something like this:

```
replacements:
    kok:
        name: "kok"
        alias: [alias1, alias2,...]
        char: ""
    kappa:
        name: "Kappa"
        alias: [alias1, alias2,...]
        char: ""
```
i think this would be a good solution
