### ISSUE TITLE
The /emotes list is no longer displayed

### ISSUE THREAD

**Issue by M1B4ND** [felixstaude/Emotes#6]
Hello, I can't see the list. Is it the same on your side, or have I done something wrong?
![image](https://github.com/felixstaude/Emotes/assets/70129787/eb60ded2-92b0-4f8c-83ea-8683df4b5206)

My config.yml
```
replacements:
  kappa:
    names: [":Kappa:", ":kappa:", "kappa", "Kappa"]
    char: "\ue001"
  kekw:
    names: [":kekw:", ":KEKW:", "kekw", "KEKW"]
    char: "\ue002"
```
Before the list was displayed when I did **/emotes** but _maybe_ since the new list structure it doesn't work anymore.
> And thanks for the translation.
